- hosts: all
  remote_user: root
  roles:
  - firewall

- hosts: master-redis
  remote_user: root
  roles:
  - master-redis
  - sentinels

- hosts: slaves-redis
  remote_user: root
  roles:
  - sentinels
  - slaves-redis
