---
- name: Make redis sentinel configuration
  template:
    src: redis-sentinel.conf.j2
    dest: "{{ redis_sentinel_src_vol }}/sentinel.conf"
    backup: yes


- name: Configuration FirewallD
  firewalld:
    zone: trusted
    interface: docker0
    immediate: yes
    permanent: yes
    state: enabled


- name: Deploy redis sentinel docker container
  docker_container:
        name: "sentinel-{{ container_name }}"
        hostname: "{{ container_name }}-sentinel"
        image: "{{ redis_sentinel_docker_image_name }}"
        published_ports:
          - "{{ sentinel_port }}:26379"
        volumes:
          - "{{ redis_sentinel_src_vol }}:/data"
        restart_policy: always
