---
- name: Make redis master configuration
  template:
    src: redis.conf.j2
    dest: "{{ redis_src_vol }}/redis.conf"
    backup: yes

#firewall-cmd --permanent --add-interface=docker0 --zone=public

- name: Configuration FirewallD
  firewalld:
    zone: trusted
    interface: docker0
    immediate: yes
    permanent: yes
    state: enabled


- name: Deploy master redis docker container
  docker_container:
        name: "{{ container_name }}"
        hostname: "{{ container_name }}"
        image: "{{ redis_docker_image_name }}"
        published_ports:
          - "{{ master_redis_src_port }}:6379"
        volumes:
          - "{{ redis_src_vol }}:/data"
        restart_policy: always
