---
- name: Make redis slave configuration
  template:
    src: redis.conf.j2
    dest: "{{ redis_src_vol }}"
  backup: yes


- name: Deploy slave redis docker container
  docker_container:
        name: "{{ container_name }}"
        hostname: "{{ container_name }}"
        image: "{{ redis_docker_image_name }}"
        published_ports:
          - "{{ redis_port }}:6379"
        volumes:
          - "{{ redis_src_vol }}:/data"
        restart_policy: always
